### ISSUE TITLE
[Question] Will it run out memory or break the system if a bunch of books converting at the same time?

### ISSUE THREAD

**Issue by nguyen47** [JVKdouk/node-ebook-converter#6]
Hi, I am really appreciate when you create this package. I have a question to ask you that will it run out memory or break the system if a bunch of books converting at the same time?
For example: I'm converting one 50 books in one request and 20 others in other request?

Thank you so much for your help.

**Comment by JVKdouk** [comment]
Thank you for the support!
It won't run out of memory. This library has a queue system that, instead of converting all of the documents at the same time, it breaks it down into a queue. You can convert more than one at the same time by setting the pool size. I advise you to not set the pool size to a number greater than the available threads in your CPU.
